### ISSUE TITLE
Buffer.alloc dependencies breaking test

### ISSUE THREAD

**Issue by lamchakchan** [xogroup/felicity#41] opened 2016-10-29 19:16 UTC
```
Failed tests:

  11) Felicity Example should return a buffer:

      Buffer.alloc is not a function

      at Object.internals.string.internals.number.internals.binary.schema [as binary] (/Users/lchan/Projects/felicity/lib/helpers.js:323:110)
      at Object.exampleGenerator [as example] (/Users/lchan/Projects/felicity/lib/exampleGenerator.js:16:138)
      at /Users/lchan/Projects/felicity/test/felicity_tests.js:92:34
      at Immediate._onImmediate (/Users/lchan/Projects/felicity/node_modules/lab/lib/runner.js:647:36)
      at processImmediate [as _immediateCallback] (timers.js:383:17)

  84) Binary should return a buffer:

      Buffer.alloc is not a function

      at Object.internals.string.internals.number.internals.binary.schema [as binary] (/Users/lchan/Projects/felicity/lib/helpers.js:323:110)
      at /Users/lchan/Projects/felicity/test/value_generator_tests.js:514:40
      at Immediate._onImmediate (/Users/lchan/Projects/felicity/node_modules/lab/lib/runner.js:647:36)
      at processImmediate [as _immediateCallback] (timers.js:383:17)

  85) Binary should return a string with specified encoding:

      Buffer.alloc is not a function

      at Object.internals.string.internals.number.internals.binary.schema [as binary] (/Users/lchan/Projects/felicity/lib/helpers.js:323:110)
      at /Users/lchan/Projects/felicity/test/value_generator_tests.js:534:44
      at Array.forEach (native)
      at /Users/lchan/Projects/felicity/test/value_generator_tests.js:531:28
      at Immediate._onImmediate (/Users/lchan/Projects/felicity/node_modules/lab/lib/runner.js:647:36)
      at processImmediate [as _immediateCallback] (timers.js:383:17)

  86) Binary should return a buffer of minimum size:

      Buffer.alloc is not a function

      at Object.internals.string.internals.number.internals.binary.schema [as binary] (/Users/lchan/Projects/felicity/lib/helpers.js:323:110)
      at /Users/lchan/Projects/felicity/test/value_generator_tests.js:546:40
      at Immediate._onImmediate (/Users/lchan/Projects/felicity/node_modules/lab/lib/runner.js:647:36)
      at processImmediate [as _immediateCallback] (timers.js:383:17)

  87) Binary should return a buffer of maximum size:

      Buffer.alloc is not a function

      at Object.internals.string.internals.number.internals.binary.schema [as binary] (/Users/lchan/Projects/felicity/lib/helpers.js:323:110)
      at /Users/lchan/Projects/felicity/test/value_generator_tests.js:554:40
      at Immediate._onImmediate (/Users/lchan/Projects/felicity/node_modules/lab/lib/runner.js:647:36)
      at processImmediate [as _immediateCallback] (timers.js:383:17)

  88) Binary should return a buffer of specified size:

      Buffer.alloc is not a function

      at Object.internals.string.internals.number.internals.binary.schema [as binary] (/Users/lchan/Projects/felicity/lib/helpers.js:323:110)
      at /Users/lchan/Projects/felicity/test/value_generator_tests.js:562:40
      at Immediate._onImmediate (/Users/lchan/Projects/felicity/node_modules/lab/lib/runner.js:647:36)
      at processImmediate [as _immediateCallback] (timers.js:383:17)

  89) Binary should return a buffer of size between min and max:

      Buffer.alloc is not a function

      at Object.internals.string.internals.number.internals.binary.schema [as binary] (/Users/lchan/Projects/felicity/lib/helpers.js:323:110)
      at /Users/lchan/Projects/felicity/test/value_generator_tests.js:571:40
      at Immediate._onImmediate (/Users/lchan/Projects/felicity/node_modules/lab/lib/runner.js:647:36)
      at processImmediate [as _immediateCallback] (timers.js:383:17)

  122) Object should return an object with specified keys:

      Buffer.alloc is not a function

      at Object.internals.string.internals.number.internals.binary.schema [as binary] (/Users/lchan/Projects/felicity/lib/helpers.js:323:110)
      at /Users/lchan/Projects/felicity/lib/helpers.js:499:147
      at Array.forEach (native)
      at Object.internals.string.internals.number.internals.binary.internals.date.internals.array.internals.object.Object.keys.forEach.schemaDescription.rules.forEach.schemaDescription.dependencies.forEach.peers.forEach [as object] (/Users/lchan/Projects/felicity/lib/helpers.js:483:126)
      at /Users/lchan/Projects/felicity/test/value_generator_tests.js:960:40
      at Immediate._onImmediate (/Users/lchan/Projects/felicity/node_modules/lab/lib/runner.js:647:36)
      at processImmediate [as _immediateCallback] (timers.js:383:17)


8 of 131 tests failed
Test duration: 389 ms
Assertions count: 1575 (verbosity: 12.02)
No global variable leaks detected
Coverage: 99.87% (1/754)
lib/helpers.js missing coverage on line(s): 329
Code coverage below threshold: 99.87 < 100
Linting results: No issues

npm ERR! Test failed.  See above for more details.
```

**Comment by WesTyler** [comment] 2016-10-29 20:17
Oh dang, that's right, there is a Node version dependency.

At minimum this should be in the README; I may even polyfill `buffer.alloc`.

**Comment by WesTyler** [comment] 2016-10-29 20:29
Also: Node versions required to avoid polyfill:

- v4.5.x + 
- v5.10.x+
- v6.0.x+
- v7.0.x+

**Comment by WesTyler** [comment] 2016-10-29 20:45
Node version dependencies added to the `Setting up for development` portion of the README.

@lamchakchan do you think a `Buffer.alloc` polyfill is needed to remove the Node version dependency?

**Comment by lamchakchan** [comment] 2016-10-29 20:49
We should definitely polyfill `Buffer.alloc`.  Keep this issue alive for that.

**Comment by devinivy** [comment] 2016-10-29 21:24
As noted on Lam's PR, there's also a package.json field to enforce nodejs version: https://docs.npmjs.com/files/package.json#engines

I'd also suggest not actually polyfilling `alloc()`, but rather use a module like that provides the functionality you want, such as https://www.npmjs.com/package/buffer-alloc.

**Comment by WesTyler** [comment] 2016-10-29 22:43
Awesome, thanks guys. 

Since Lam implemented buffer-alloc, I'm going to remove the Node dependency info from the README and close this issue. Also not going to add the engines field since the issue is resolved.

**Comment by lamchakchan** [comment] 2016-10-29 22:44
great!

**Closed** 2016-10-29 22:45 UTC
Labels: dependency, documentation, enhancement
